# Generated by Django 5.2.4 on 2025-07-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_exercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excerises', models.CharField(choices=[(4, 'squats'), (5, 'push-ups'), (6, 'deadlifts'), (7, 'lunges'), (8, 'plank'), (9, 'bench press'), (10, 'burpees'), (11, 'mountain climbers'), (12, 'pull-ups'), (13, 'bicep curls')])),
                ('clients', models.CharField(choices=[(1, 'er'), (2, 'asdvb'), (3, 'asdvb'), (4, 'asdf')])),
            ],
        ),
    ]
