# Generated by Django 5.2.4 on 2025-07-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='clients',
            field=models.CharField(choices=[('er', 1), ('asdvb', 2), ('asdvb', 3), ('asdf', 4)]),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='excerises',
            field=models.CharField(choices=[('squats', 4), ('push-ups', 5), ('deadlifts', 6), ('lunges', 7), ('plank', 8), ('bench press', 9), ('burpees', 10), ('mountain climbers', 11), ('pull-ups', 12), ('bicep curls', 13)]),
        ),
    ]
