# Generated by Django 5.2.4 on 2025-07-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_trainer_clients_alter_trainer_excerises'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='clients',
            new_name='clients_id',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='excerises',
            new_name='excerises_id',
        ),
    ]
