# Generated by Django 5.2.4 on 2025-07-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_clients_trainer_clients_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='clients_id',
            new_name='cd_id',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='excerises_id',
            new_name='ex_id',
        ),
    ]
