# Generated by Django 5.2.4 on 2025-07-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='exercises',
            field=models.ManyToManyField(to='api.exercise'),
        ),
    ]
