# Generated by Django 5.2.4 on 2025-07-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_trainer_clients_alter_trainer_excerises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='clients',
            field=models.CharField(choices=[(1, 'er'), (2, 'asdvb'), (3, 'asdvb'), (4, 'asdf')]),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='excerises',
            field=models.CharField(choices=[(4, 'squats'), (5, 'push-ups'), (6, 'deadlifts'), (7, 'lunges'), (8, 'plank'), (9, 'bench press'), (10, 'burpees'), (11, 'mountain climbers'), (12, 'pull-ups'), (13, 'bicep curls')]),
        ),
    ]
