# Generated by Django 5.2.4 on 2025-07-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_clients_id_trainer_cd_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='cd_id',
            new_name='c_id',
        ),
    ]
